version: 2
models:
  - name: nba_player_info
    columns:
      - name: player_id
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: team_name
      - name: position
      - name: height
      - name: weight
  - name: nba_player_game_logs
    tests:
      - elementary.freshness_anomalies:
          timestamp_column: loaded_at_dttm # Mandatory
          time_bucket: # Daily by default
            period: day
            count: 1
      - elementary.all_columns_anomalies:
          tags: ["elementary"]
      - elementary.volume_anomalies:
          fail_on_zero: false
          tags: ["elementary"]
      - elementary.dimension_anomalies:
          dimensions: ['player_id', 'team_id', 'game_id']
          tags: ["elementary"]
      - elementary.event_freshness_anomalies:
          event_timestamp_column: game_date
          update_timestamp_column: loaded_at_dttm
          tags: ["elementary"]

